# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV['GMAIL_USERNAME'] %>
  email_provider_password: <%= ENV['GMAIL_PASSWORD'] %>
  mailchip_api_key: <%= ENV['MAILCHIP_API_KEY'] %>
  mailchip_list_id: <%= ENV['MAILCHIP_LIST_ID'] %>
  domain_name: example.com
  owner_email: <%= ENV['OWNER_EMAIL'] %>
  secret_key_base: 64af0f1901d6633f81b36f64e1f2985d6d3b8443fc064c48f340d539d4e508eb4426918a9764ca2d6c6720786d40f1f88ae8c5efe0a2f61c8886b81f97075e32


test:
  secret_key_base: 0dba04a2697e538af683d36ec6f5917543a97856610085c8a20bdc6721ab9c28e709e729b2593f9fbfc1d9e9021deb96e86ec168f974c50bda03a5f2546b7f09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV['GMAIL_USERNAME'] %>
  email_provider_password: <%= ENV['GMAIL_PASSWORD'] %>
  mailchip_api_key: <%= ENV['MAILCHIP_API_KEY'] %>
  mailchip_list_id: <%= ENV['MAILCHIP_LIST_ID'] %>
  domain_name: example.com
  owner_email: <%= ENV['OWNER_EMAIL'] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
